### DISCUSSION TITLE
Sample docker-compose.yml for ibgateway with secrets support

### DISCUSSION THREAD

**Discussion by gnzsnz** [gnzsnz/ib-gateway-docker#103] [Show and tell]
This is a sample `docker-compose.yml` to use secrets on [ibgateway](https://github.com/users/gnzsnz/packages/container/package/ib-gateway).

Please take into account that this example:
- uses `latest` image, you can replace `latest` with `stable`
- VNC port is exposed, make sure you understand the security implications. 
- the `.env` file uses `TRADING_MODE=both`.

```yml
name: algo-trader
services:
  ib-gateway:
    restart: unless-stopped
    build:
      context: ./latest
      tags:
        - "ghcr.io/gnzsnz/ib-gateway:latest"
    image: ghcr.io/gnzsnz/ib-gateway:latest
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD:-}
      TWS_PASSWORD_FILE: ${TWS_PASSWORD_FILE:-}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_USERID_PAPER: ${TWS_USERID_PAPER:-}
      TWS_PASSWORD_PAPER: ${TWS_PASSWORD_PAPER:-}
      TWS_PASSWORD_PAPER_FILE: ${TWS_PASSWORD_PAPER_FILE:-}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      VNC_SERVER_PASSWORD_FILE: ${VNC_SERVER_PASSWORD_FILE:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_PASSPHRASE_FILE: ${SSH_PASSPHRASE_FILE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}
    secrets:
      - tws_password
      - tws_password_paper
      - ssh_passphrase
      - vnc_password
    volumes:
#      - ${PWD}/jts.ini:/home/ibgateway/Jts/jts.ini
#      - ${PWD}/config.ini:/home/ibgateway/ibc/config.ini
      - ${PWD}/tws_settings/:${TWS_SETTINGS_PATH:-/home/ibgateway/tws_settings}
      - ${PWD}/ssh/:/home/ibgateway/.ssh
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "5900:5900"

secrets:
  tws_password:
    file: pass/tws_password.txt
  tws_password_paper:
    file: pass/tws_password_paper.txt
  ssh_passphrase:
    file: pass/ssh_password.txt
  vnc_password:
    file: pass/vnc_password.txt

```

with a sample `.env` file
```
# live
TWS_USERID=
#TWS_PASSWORD=
#TRADING_MODE=live
#
TRADING_MODE=both
# paper
#TWS_USERID=
#TWS_PASSWORD=
TWS_PASSWORD_FILE=/run/secrets/tws_password
#TRADING_MODE=paper
#
TWS_USERID_PAPER=
#TWS_PASSWORD_PAPER=
TWS_PASSWORD_PAPER_FILE=/run/secrets/tws_password_paper
#TWS_SETTINGS_PATH=/config/tws_settings
TWS_SETTINGS_PATH=/home/ibgateway/tws_settings
READ_ONLY_API=no
#VNC_SERVER_PASSWORD=
VNC_SERVER_PASSWORD_FILE=/run/secrets/vnc_password
TWOFA_TIMEOUT_ACTION=restart
AUTO_RESTART_TIME=01:24 AM
RELOGIN_AFTER_2FA_TIMEOUT=yes
TIME_ZONE=Europe/Zurich
CUSTOM_CONFIG=
BYPASS_WARNING=yes
JAVA_HEAP_SIZE=1024
# SSH yes,both
SSH_TUNNEL=both
SSH_OPTIONS=
SSH_ALIVE_INTERVAL=
SSH_ALIVE_COUNT=
#SSH_PASSPHRASE=
SSH_PASSPHRASE_FILE=/run/secrets/ssh_passphrase
SSH_REMOTE_PORT=
SSH_USER_TUNNEL=
SSH_RESTART=
SSH_VNC_PORT=5900
SSH_RDP_PORT=3389
PASSWD_FILE=/run/secrets/abc_password

```
