### DISCUSSION TITLE
Sample docker-compose.yml for tws-rdesktop with secrets support

### DISCUSSION THREAD

**Discussion by gnzsnz** [gnzsnz/ib-gateway-docker#105] [Show and tell]
This is a sample `docker-compose.yml` to use secrets on [tws-rdesktop](https://github.com/users/gnzsnz/packages/container/package/tws-rdesktop) image.

Please take into account that this example:

- uses latest image, you can replace latest with stable
- RDP port is exposed, make sure you understand the security implications.
- the `.env` file uses TRADING_MODE=both.

```yml
name: algo-trader
services:
  tws:
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri #recommended
    shm_size: "1gb" #recommended
    security_opt:
      - seccomp:unconfined #recommended
    build:
      context: ./latest
      dockerfile: Dockerfile.tws
      tags:
        - "ghcr.io/gnzsnz/tws-rdesktop:latest"
    image: ghcr.io/gnzsnz/tws-rdesktop:latest
    environment:
      PUID: 1000
      PGID: 1000
      PASSWD: ${PASSWD:-}
      PASSWD_FILE: ${PASSWD_FILE:-}
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD:-}
      TWS_PASSWORD_FILE: ${TWS_PASSWORD_FILE:-}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_USERID_PAPER: ${TWS_USERID_PAPER:-}
      TWS_PASSWORD_PAPER: ${TWS_PASSWORD_PAPER:-}
      TWS_PASSWORD_PAPER_FILE: ${TWS_PASSWORD_PAPER_FILE:-}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      READ_ONLY_API: ${READ_ONLY_API:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_PASSPHRASE_FILE: ${SSH_PASSPHRASE_FILE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_RDP_PORT: ${SSH_RDP_PORT:-}
    secrets:
      - tws_password
      - tws_password_paper
      - ssh_passphrase
      - vnc_password
      - abc_password
    volumes:
      - ./config:/config # optional
      - tws_tmp:/tmp # recommended for performance
    # custom certificate and key
    #- ${PWD}/keylock:/keylock # required to avoid key generation by container
    #- ${PWD/key.pem:/etc/xrdp/key.pem # key
    #- ${PWD}/cert.pem:/etc/xrdp/cert.pem # cert
    ports:
      - "127.0.0.1:7496:7498" # live
      - "127.0.0.1:7497:7499" # paper
      - "3370:3389" # xrdp

volumes:
  tws_tmp:

secrets:
  tws_password:
    file: pass/tws_password.txt
  tws_password_paper:
    file: pass/tws_password_paper.txt
  ssh_passphrase:
    file: pass/ssh_password.txt
  vnc_password:
    file: pass/vnc_password.txt
  abc_password:
    file: pass/abc_password.txt

```

with a sample `.env` file

```
# live
TWS_USERID=
#TWS_PASSWORD=
#TRADING_MODE=live
#
TRADING_MODE=both
# paper
#TWS_USERID=
#TWS_PASSWORD=
TWS_PASSWORD_FILE=/run/secrets/tws_password
#TRADING_MODE=paper
#
TWS_USERID_PAPER=
#TWS_PASSWORD_PAPER=
TWS_PASSWORD_PAPER_FILE=/run/secrets/tws_password_paper
#TWS_SETTINGS_PATH=/config/tws_settings
TWS_SETTINGS_PATH=/home/ibgateway/tws_settings
READ_ONLY_API=no
#VNC_SERVER_PASSWORD=
VNC_SERVER_PASSWORD_FILE=/run/secrets/vnc_password
TWOFA_TIMEOUT_ACTION=restart
AUTO_RESTART_TIME=01:24 AM
RELOGIN_AFTER_2FA_TIMEOUT=yes
TIME_ZONE=Europe/Zurich
CUSTOM_CONFIG=
BYPASS_WARNING=yes
JAVA_HEAP_SIZE=1024
# SSH yes,both
SSH_TUNNEL=both
SSH_OPTIONS=
SSH_ALIVE_INTERVAL=
SSH_ALIVE_COUNT=
#SSH_PASSPHRASE=
SSH_PASSPHRASE_FILE=/run/secrets/ssh_passphrase
SSH_REMOTE_PORT=
SSH_USER_TUNNEL=
SSH_RESTART=
SSH_VNC_PORT=5900
SSH_RDP_PORT=3389
PASSWD_FILE=/run/secrets/abc_password
```
