### DISCUSSION TITLE
Connect to the IBGateway failed - aarch

### DISCUSSION THREAD

**Discussion by kooyear** [gnzsnz/ib-gateway-docker#113] [Q&A] [answered]
## Describe the bug

If followed the documentation, and docker-compose up to run the contianer, and try to connect to it, but I got following error

ib-gateway_1  | 2024-05-18 07:29:31:800 IBC: Waiting for config dialog future to complete
ib-gateway_1  | 2024-05-18 07:29:31:800 IBC: Getting main window
ib-gateway_1  | 2024-05-18 07:29:31:800 IBC: Creating main window future
ib-gateway_1  | 2024-05-18 07:29:32:452 IBC: detected frame entitled: IBKR Gateway; event=Opened
ib-gateway_1  | 2024-05-18 07:29:32:453 IBC: Login dialog WINDOW_OPENED: LoginState is LOGGED_OUT
ib-gateway_1  | 2024-05-18 07:29:32:453 IBC: trading mode from settings: tradingMode=live
ib-gateway_1  | 2024-05-18 07:29:32:453 IBC: Setting Trading mode = live
ib-gateway_1  | 2024-05-18 07:29:32:532 IBC: Setting user name
ib-gateway_1  | 2024-05-18 07:29:32:532 IBC: Setting password
ib-gateway_1  | 2024-05-18 07:29:32:533 IBC: Login attempt: 1
ib-gateway_1  | 2024-05-18 07:29:32:533 IBC: detected frame entitled: IBKR Gateway; event=Activated
ib-gateway_1  | 2024-05-18 07:29:32:535 IBC: detected frame entitled: IBKR Gateway; event=Focused
ib-gateway_1  | 2024-05-18 07:29:32:552 IBC: Click button: Log In
ib-gateway_1  | 2024-05-18 07:29:33:692 IBC: detected frame entitled: IBKR Gateway; event=Lost focus
ib-gateway_1  | 2024-05-18 07:29:33:693 IBC: detected frame entitled: IBKR Gateway; event=Deactivated
ib-gateway_1  | 2024-05-18 07:29:33:693 IBC: detected frame entitled: Loading...; event=Activated
ib-gateway_1  | 2024-05-18 07:29:33:698 IBC: detected frame entitled: Loading...; event=Focused
ib-gateway_1  | 2024-05-18 07:29:33:698 IBC: detected frame entitled: Loading...; event=Opened
ib-gateway_1  | 2024-05-18 07:29:33:698 IBC: Found Gateway main window
ib-gateway_1  | 2024-05-18 07:29:33:699 IBC: Got main window from future
ib-gateway_1  | 2024-05-18 07:29:33:699 IBC: Invoking config dialog menu
ib-gateway_1  | 2024/05/18 07:29:34 socat[116] E connect(5, AF=2 127.0.0.1:4001, 16): Connection refused
ib-gateway_1  | 2024-05-18 07:29:34:412 IBC: detected frame entitled: Loading...; event=Lost focus
ib-gateway_1  | 2024-05-18 07:29:34:413 IBC: detected frame entitled: Loading...; event=Deactivated
ib-gateway_1  | 2024-05-18 07:29:34:413 IBC: detected frame entitled: Connecting to server (trying for another 19 seconds)...; event=Activated
ib-gateway_1  | 2024-05-18 07:29:34:415 IBC: detected frame entitled: Connecting to server (trying for another 19 seconds)...; event=Focused
ib-gateway_1  | 2024-05-18 07:29:34:415 IBC: detected frame entitled: Connecting to server (trying for another 19 seconds)...; event=Opened
ib-gateway_1  | 2024-05-18 07:29:36:004 IBC: detected dialog entitled: Second Factor Authentication; event=Opened
ib-gateway_1  | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ib-gateway_1  | 2024-05-18 07:29:36:004 IBC: You should specify the required second factor device using the SecondFactorDevice setting in config.ini
ib-gateway_1  | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ib-gateway_1  | 2024-05-18 07:29:36:004 IBC: detected frame entitled: Authenticating...; event=Lost focus
ib-gateway_1  | 2024-05-18 07:29:36:004 IBC: detected frame entitled: Authenticating...; event=Deactivated
ib-gateway_1  | 2024-05-18 07:29:36:005 IBC: detected dialog entitled: Second Factor Authentication; event=Activated
ib-gateway_1  | 2024-05-18 07:29:36:006 IBC: detected dialog entitled: Second Factor Authentication; event=Focused

just want to understand, is it the VNC is up and running, if I can login to the VNC UI to see what happend, I try to access 127.0.0.1:5900, there is not response on the browser

the .env as below

TWS_USERID=<userid>
TWS_PASSWORD=<password>
# ib-gateway
#TWS_SETTINGS_PATH=/home/ibgateway/Jts
# tws
#TWS_SETTINGS_PATH=/config/tws_settings
TWS_SETTINGS_PATH=
TRADING_MODE=live
READ_ONLY_API=no
VNC_SERVER_PASSWORD=myVncPassword
TWOFA_TIMEOUT_ACTION=restart
BYPASS_WARNING=
AUTO_RESTART_TIME=11:59 PM
AUTO_LOGOFF_TIME=
SAVE_TWS_SETTINGS=
RELOGIN_AFTER_2FA_TIMEOUT=yes
TIME_ZONE=Europe/Zurich
CUSTOM_CONFIG=
SSH_TUNNEL=
SSH_OPTIONS=
SSH_ALIVE_INTERVAL=
SSH_ALIVE_COUNT=
SSH_PASSPHRASE=
SSH_REMOTE_PORT=
SSH_USER_TUNNEL=
SSH_RESTART=
SSH_VNC_PORT=

## To Reproduce

Steps to reproduce the behavior. Please include information related to docker,
ex docker run command, .env file, docker-compose.yml.

Please provide the output of `docker compose config`

## Container logs

If applicable, add the container logs `docker logs <CONTAINER>` or
`docker-compose logs` to help explain your problem.

## Versions

Please complete the following information:

- OS: [e.g. Windows]
- Docker version: [e.g. chrome, safari]
- Image Tag (`docker image inspect ghcr.io/gnzsnz/ib-gateway:tag`): [e.g.
  latest]
- Image Digest (`docker images --digests`): [e.g.
  sha256:60d9d54009b1b66908bbca1ebf5b8a03a39fe0cb35c2ab4023f6e41b55d17894]

## Additional context

What have you tried and failed.

My primary objective is to fix any bug on the container, ex Dockerfile, run.sh
script, docker-compose.yml. Please don't expect upstream issues to be solved
here (ex. IB gateway, IBC, etc)

**Comment by gnzsnz** [comment]
Depending on what you did on your docker-compose.yml you might be able to log into VNC. based on the `.env` file that you provided, yes VNC should be up and running. is it accessible from the network? that depends on your `docker-compose.yml`

Please provide the output of `docker compose config` and `docker images --digests`, and please make sure that you are using an up to date tag `latest` or `stable`

**Comment by kooyear** [comment]
Thanks for your reply, my docker-compose.yml file as below

```
version: "3.4"
services:
  ib-gateway:
    restart: always
    build:
      context: ./latest
    image: ghcr.io/gnzsnz/ib-gateway:latest
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_USERID_PAPER: ${TWS_USERID_PAPER:-}
      TWS_PASSWORD_PAPER: ${TWS_PASSWORD_PAPER:-}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "5900:5900"
```

and yes I use the latest tag, what I don't understand is when I launched IB Gateway through GUI before, it ask me to verify through SNS message, but if you put IB Gateway, how to implement the SNS message authentication?  and how do you connect to VNC? through browser? I had some VNC image before, I can connect it through the browser, but looks it failed on this one. not very sure where I am wrong in which steps.

and when I run the python to test the connection to that docker container, I can see the log message as below
`ib-gateway_1  | 2024/05/18 11:05:00 socat[136] E connect(5, AF=2 127.0.0.1:4001, 16): Connection refused`

and the connection is timeout and failed

**Comment by gnzsnz** [comment]
Please provide the output of `docker compose config` and `docker images --digests`

**Comment by kooyear** [comment]
docker compose config as below (TWS_USERID, TWS_PASSWORD I hide the values)
```
name: ib-gateway-docker
services:
  ib-gateway:
    build:
      context: /Users/yegu/Projects/smartoption-auto-trade/ib-gateway-docker/latest
      dockerfile: Dockerfile
    environment:
      AUTO_LOGOFF_TIME: ""
      AUTO_RESTART_TIME: 11:59 PM
      BYPASS_WARNING: ""
      CUSTOM_CONFIG: "NO"
      JAVA_HEAP_SIZE: ""
      READ_ONLY_API: "no"
      RELOGIN_AFTER_TWOFA_TIMEOUT: "no"
      SAVE_TWS_SETTINGS: ""
      SSH_ALIVE_COUNT: ""
      SSH_ALIVE_INTERVAL: ""
      SSH_OPTIONS: ""
      SSH_PASSPHRASE: ""
      SSH_REMOTE_PORT: ""
      SSH_RESTART: ""
      SSH_TUNNEL: ""
      SSH_USER_TUNNEL: ""
      SSH_VNC_PORT: ""
      TIME_ZONE: Europe/Zurich
      TRADING_MODE: live
      TWOFA_EXIT_INTERVAL: "60"
      TWOFA_TIMEOUT_ACTION: restart
      TWS_PASSWORD: <password>
      TWS_PASSWORD_PAPER: ""
      TWS_SETTINGS_PATH: ""
      TWS_USERID: <username>
      TWS_USERID_PAPER: ""
      TZ: Europe/Zurich
      VNC_SERVER_PASSWORD: myVncPassword
    image: ghcr.io/gnzsnz/ib-gateway:latest
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 4003
      published: "4001"
      protocol: tcp
    - mode: ingress
      host_ip: 127.0.0.1
      target: 4004
      published: "4002"
      protocol: tcp
    - mode: ingress
      target: 5900
      published: "5900"
      protocol: tcp
    restart: always
networks:
  default:
    name: ib-gateway-docker_default
```

docker images --digests as below

REPOSITORY                    TAG       DIGEST                                                                    IMAGE ID       CREATED         SIZE
ghcr.io/gnzsnz/ib-gateway     latest    <none>                                                                    abe609e3b3dc   5 hours ago     786MB
