### DISCUSSION TITLE
Configure reconnect interval?

### DISCUSSION THREAD

**Discussion by iitsoftware** [gnzsnz/ib-gateway-docker#168] [Q&A]
I got it working on my paper account. However, when I want to check my positions through the app, the gateway immediately reconnects and kicks me out.

Is there a way to configure reconnect? Or, better, to have API and app connected at the same time?

I have already configured read-only.

**Comment by gnzsnz** [comment]
It depends heavily on your code. So it's not easy to give you something specific.

Personally i use [ib_async](https://github.com/ib-api-reloaded/ib_async/) paired with [tenacity](https://tenacity.readthedocs.io/en/latest/) it works like a charm.

Regarding why it gets disconnected, again difficult to say. you ask about having api and app connected. this container does exactly that with ibgateway or tws. you can can even run paper and live in parallel. are you trying to run paper and login somewhere else to live? that could explain your issues.

**Comment by edgebroker** [comment]
I don't mean my client connection.

I run the IB gateway with this docker compose settings:

```
ib-gateway:
    platform: linux/amd64
    image: ghcr.io/gnzsnz/ib-gateway:stable
    restart: unless-stopped
    environment:
      TWS_USERID: xxx 
      TWS_PASSWORD: xxx
      TRADING_MODE: paper 
      READ_ONLY_API: yes
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002"
```


So it's connected to my paper account in r/o mode.

From time to time I need to check my positions on my paper account via the IBKR app. So when I login there, it tells me someone else is already connected (obviously the IB gateway) und I'm being asked whether to drop that other connection. I hit yes, the app drops the other connection and I can login for a second until the gateway does the same with my app when it reconnects:

```
ibgateway-ib-gateway-1  | 2024-09-16 13:31:45:404 IBC: detected frame entitled: Starting application...; event=Lost focus
ibgateway-ib-gateway-1  | 2024-09-16 13:31:45:404 IBC: detected frame entitled: Starting application...; event=Deactivated
ibgateway-ib-gateway-1  | 2024-09-16 13:31:45:405 IBC: detected frame entitled: Starting application...; event=Closed

```
My app works fine after I stopped the gateway.
