### DISCUSSION TITLE
Can't make requests from other containers in the same docker network

### DISCUSSION THREAD

**Discussion by jussirantala** [gnzsnz/ib-gateway-docker#219] [Q&A] [answered]
I have a Python script which uses `ib_async`. 

When I run `ghcr.io/gnzsnz/ib-gateway:stable` with docker compose, I can successfully connect to it from my Python script and do requests by using `localhost:8888`. 

If I run the Python script in Docker using the same docker compose file (and the same default network), the script will get `connection refused` error for all requests.

The port is opened with `127.0.0.1:8888:4003` and I use live account. I connect to it by using its container name and port `8888` as supposed to. I do receive some stuff from the container when connecting, just can't make any requests for example for getting open positions.

I don't have this issue with any other dockerized IB GWs (for example [this](https://github.com/extrange/ibkr-docker)) so it must be a bug I guess?

**Comment by gnzsnz** [comment]
This works fine, i use it every day. there must be an error on your docker-compose or in the way you are using the API.

what do you mean by `localhost:8888` or `127.0.0.1:8888:4003`, I can't help you the level of detail provided.

Regarding how to use a script in as a separate service, please check #83 for an example

**Comment by jussirantala** [comment]
Docker compose:
```
version: "3.4"
services:
  ib-insync-trader:
    container_name: ib-insync-trader
    build:
      context: ./ib-insync
      dockerfile: Dockerfile.develop
    ports:
      - 5005:5005
    volumes:
      - ./ib-insync/app.py:/app/app.py
    restart: always
    environment:
     - IB_PORT=8888
     - PORT=5005
     - IB_ACCOUNT=UXXXXXXXX
     - CLIENT_ID=0
     - IB_HOST=ib-gateway
    ports: 
      - "127.0.0.1:5005:5005"
    healthcheck:
        test: "curl -X GET --fail http://localhost:5005/health -k || exit 1"
        interval: 10s
        timeout: 5s
        start_period: 3s     
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
  ib-gateway:
    container_name: ib-gateway
    restart: always
    image: ghcr.io/gnzsnz/ib-gateway:stable
    env_file:
      - ./envs/agent/ib2.env
    ports:
      - "127.0.0.1:8888:4003"
```

If I run the docker compose and use my python script outside docker (just with `python3 ./app.py`) and connect to `localhost:8888`, it works fine so the GW configuration is ok.

But if I use the python script inside the above docker compose, it tries `ib-gateway:8888` but all requests get `Connection refused` error.

If I replace IB GW with for example [this](https://github.com/extrange/ibkr-docker) other docker image, there's no issues inside docker network.
