### DISCUSSION TITLE
Usage question: configuring ports and waiting for login

### DISCUSSION THREAD

**Discussion by jackroc97** [gnzsnz/ib-gateway-docker#224] [Q&A] [answered]
I am trying to put together a simple example of using this container, but I am running into some issues.  I think they ultimately boil down to me incorrectly configuring ports.  I will note that I am using the [ib_async](https://github.com/ib-api-reloaded/ib_async) wrapper for accessing the api.

My application consists of the following files:
* **docker-compose.yml** (A modified version of the provided template, which adds a service for my "bot".)
* **dockerfile** (Dockerfile for my bot)
* **main.py** (The bot: a simple python script which attempts to start an IB Gateway connection and check account state)

Here are the contents of the files:

**docker-compose.yml**
```yml
name: algo-trader
services:
  ib-gateway:
    # Here i use the unmodified ib-gateway service provided by this repo
  bot:
    build: .
    environment:
      GATEWAY_HOST: "0.0.0.0"
      GATEWAY_PORT: 4004
```

**dockerfile**
```docker
FROM python:3.11
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 4001 4002 4003 4004
CMD ["python", "main.py"]
```

**main.py**
```python
import os
import time

from ib_async import *

if __name__ == '__main__':
    
    # This is a hacky way of making sure the gateway is ready
    print("Waiting 20s for gateway to start...")
    time.sleep(20)
    
    host = os.environ["GATEWAY_HOST"] or "127.0.0.1"
    port = os.environ["GATEWAY_PORT"] or 4002
    print(f"Attempting to connect to gateway at {host}:{port}...")
    
    ib = IB()
    ib.connect(host=host, port=port, clientId=1)
    summary = ib.accountSummary()
    
    print(summary)
```
When I run the docker-compose, I get the following error: 
`bot-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 4004)`
This occurs after seeing the "Login has completed" message from ib-gateway.

Am I using the wrong IP/ports?  Additionally, is there an alternative to using the my hacky `time.sleep` work-around for making sure that the gateway is running?

**Comment by gnzsnz** [comment, marked as answer]
ib_async documentation is clear on the usage of `time.sleep` --> DON'T USE IT, please read the documentation.

not sure what's your expectation with `GATEWAY_HOST` and `GATEWAY_PORT` ibgateway does not use those values. by default you can access services by their service name (or hostname if you set it), so in this case from your bot you can access ibgateway as `ib-gateway` as that's the service name in your `docker-compose.yml` example. please check docker and docker compose documentation

**Reply by jackroc97** [reply]
Thanks for the reply @gnzsnz!  **Connecting to `ib-gateway` using `ib.connect(host="ib-gateway", port=4004, clientId=1)` solved my problem.**. To address some of the other points you brought up in your reply...
* `GATEWAY_HOST` and `GATEWAY_PORT` we're environment variables I was using to debug my application, I did not expect them to be used by `ib-gateway`.
* Thanks for point out that I should not use `time.sleep`.  I have updated my code to use `ib.sleep` instead.

I have noticed a lot of questions in this discussions page regarding connecting to `ib-gateway` from other containers.  I believe my "mini-program" that I have been using to test this may be a very helpful "Hello World" resource for people who are trying to get off the ground and, like myself, still a bit of a docker novice.  I will provide the code for my program in full below.  Thanks again!

**docker-compose.yml**
```yml
name: algo-trader
services:
  # This is the standard ib-gateway service
  ib-gateway:
    restart: always
    build:
      context: ./stable
      tags:
        - "ghcr.io/gnzsnz/ib-gateway:stable"
    image: ghcr.io/gnzsnz/ib-gateway:stable
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      TWS_ACCEPT_INCOMING: ${TWS_ACCEPT_INCOMING:-}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      TWS_COLD_RESTART: ${TWS_COLD_RESTART:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TWOFA_DEVICE: ${TWOFA_DEVICE:-}
      EXISTING_SESSION_DETECTED_ACTION: ${EXISTING_SESSION_DETECTED_ACTION:-primary}
      ALLOW_BLIND_TRADING: ${ALLOW_BLIND_TRADING:-no}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}
#    volumes:
#      - ${PWD}/jts.ini:/home/ibgateway/Jts/jts.ini
#      - ${PWD}/config.ini:/home/ibgateway/ibc/config.ini
#      - ${PWD}/tws_settings/:${TWS_SETTINGS_PATH:-/home/ibgateway/Jts}
#      - ${PWD}/ssh/:/home/ibgateway/.ssh
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "127.0.0.1:5900:5900"
      
  # This is my custom bot service which connects to ib-gateway
  bot:
    build: .
```

**dockerfile**
```text
FROM python:3.11
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 4001 4002 4003 4004
CMD ["python", "main.py"]

```

**main.py**
```python
from ib_async import *

if __name__ == '__main__':
    
    ib = IB()

    # This is a hacky way of waiting to make sure that the gateway has fully 
    # started and the user is logged-in before we start sending requests.
    # There is probably a better way to do this using docker-compose 
    # healthchecks... but I haven't quite figured that out yet.
    ib.sleep(20)
    
    ib.connect(host="ib-gateway", port=4004, clientId=1)
    summary = ib.accountSummary()
    
    print(summary)
```

**requirements.txt**
```text
eventkit==1.0.3
ib_async==1.0.3
nest-asyncio==1.6.0
numpy==2.2.2
```
