### DISCUSSION TITLE
Unable to authenticate to ib gateway - aarch64

### DISCUSSION THREAD

**Discussion by Shriken** [gnzsnz/ib-gateway-docker#240] [Q&A] [answered]
Here's my docker compose:

```name: algo-trader
services:
  ib-gateway:
    restart: unless-stopped
    image: ghcr.io/gnzsnz/ib-gateway:10.30.1t
    platform: linux/amd64
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_USERID_PAPER: ${TWS_USERID_PAPER:-}
      TWS_PASSWORD_PAPER: ${TWS_PASSWORD_PAPER:-}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      TWS_ACCEPT_INCOMING: ${TWS_ACCEPT_INCOMING:-manual}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      TWS_COLD_RESTART: ${TWS_COLD_RESTART:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TWOFA_DEVICE: ${TWOFA_DEVICE:-}
      EXISTING_SESSION_DETECTED_ACTION: ${EXISTING_SESSION_DETECTED_ACTION:-primary}
      ALLOW_BLIND_TRADING: ${ALLOW_BLIND_TRADING:-no}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}

    ports:
      - "4001:4003"
      - "4002:4004"
      - "5900:5900"
```

My docker compose config:
```
name: algo-trader
services:
  ib-gateway:
    environment:
      ALLOW_BLIND_TRADING: "no"
      AUTO_LOGOFF_TIME: ""
      AUTO_RESTART_TIME: ""
      BYPASS_WARNING: ""
      CUSTOM_CONFIG: "NO"
      EXISTING_SESSION_DETECTED_ACTION: primary
      JAVA_HEAP_SIZE: ""
      READ_ONLY_API: "no"
      RELOGIN_AFTER_TWOFA_TIMEOUT: "no"
      SAVE_TWS_SETTINGS: ""
      SSH_ALIVE_COUNT: ""
      SSH_ALIVE_INTERVAL: ""
      SSH_OPTIONS: ""
      SSH_PASSPHRASE: ""
      SSH_REMOTE_PORT: ""
      SSH_RESTART: ""
      SSH_TUNNEL: ""
      SSH_USER_TUNNEL: ""
      SSH_VNC_PORT: ""
      TIME_ZONE: Asia/Jerusalem
      TRADING_MODE: paper
      TWOFA_DEVICE: ""
      TWOFA_EXIT_INTERVAL: "60"
      TWOFA_TIMEOUT_ACTION: exit
      TWS_ACCEPT_INCOMING: manual
      TWS_COLD_RESTART: ""
      TWS_PASSWORD: <password>
      TWS_PASSWORD_PAPER: ""
      TWS_SETTINGS_PATH: ""
      TWS_USERID: <user>
      TWS_USERID_PAPER: ""
      TZ: Asia/Jerusalem
      VNC_SERVER_PASSWORD: ""
    image: ghcr.io/gnzsnz/ib-gateway:10.30.1t
    networks:
      default: null
    platform: linux/amd64
    ports:
      - mode: ingress
        target: 4003
        published: "4001"
        protocol: tcp
      - mode: ingress
        target: 4004
        published: "4002"
        protocol: tcp
      - mode: ingress
        target: 5900
        published: "5900"
        protocol: tcp
    restart: unless-stopped
networks:
  default:
    name: algo-trader_default
```
And here's the latest logs from the container:

```
ib-gateway-1  | 2025-02-22 13:23:22:488 IBC: Found Gateway main window
ib-gateway-1  | 2025-02-22 13:23:22:491 IBC: Got main window from future
ib-gateway-1  | 2025-02-22 13:23:22:494 IBC: Invoking config dialog menu
ib-gateway-1  | 2025-02-22 13:23:23:315 IBC: detected frame entitled: Loading...; event=Lost focus
ib-gateway-1  | 2025-02-22 13:23:23:324 IBC: detected frame entitled: Loading...; event=Deactivated
ib-gateway-1  | 2025-02-22 13:23:23:326 IBC: detected frame entitled: Authenticating...; event=Activated
ib-gateway-1  | 2025-02-22 13:23:23:336 IBC: detected frame entitled: Authenticating...; event=Focused
ib-gateway-1  | 2025-02-22 13:23:23:339 IBC: detected frame entitled: Authenticating...; event=Opened
ib-gateway-1  | /home/ibgateway/ibc/scripts/ibcstart.sh: line 508:    72 Killed                  "$java_path/java" -cp "$ibc_classpath" $java_vm_options$autorestart_option $entry_point "$ibc_ini" ${mode}
ib-gateway-1  | IBC returned exit status 137
ib-gateway-1  | autorestart file not found
ib-gateway-1  |
ib-gateway-1  | Gateway finished
```

I'm trying to login my paper account.
I'm able to login perfectly when using IBC alone (with my locally installed gateway of course)
So it seems like some IBC error internally, not sure why. Is there a way to debug this? VNC perhaps?
