### ISSUE TITLE
Usage question: configuring ports and waiting for login

### ISSUE THREAD

**Issue by jackroc97** [gnzsnz/ib-gateway-docker#223]
I am trying to put together a simple example of using this container, but I am running into some issues.  I think they ultimately boil down to me incorrectly configuring ports.  I will note that I am using the [ib_async](https://github.com/ib-api-reloaded/ib_async) wrapper for accessing the api.

My application consists of the following files:
* **docker-compose.yml** (A modified version of the provided template, which adds a service for my "bot".)
* **dockerfile** (Dockerfile for my bot)
* **main.py** (The bot: a simple python script which attempts to start an IB Gateway connection and check account state)

Here are the contents of the files:

**docker-compose.yml**
```yml
name: algo-trader
services:
  ib-gateway:
    # Here i use the unmodified ib-gateway service provided by this repo
  bot:
    build: .
    environment:
      GATEWAY_HOST: "0.0.0.0"
      GATEWAY_PORT: 4004
```

**dockerfile**
```docker
FROM python:3.11
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 4001 4002 4003 4004
CMD ["python", "main.py"]
```

**main.py**
```python
import os
import time

from ib_async import *

if __name__ == '__main__':
    
    # This is a hacky way of making sure the gateway is ready
    print("Waiting 20s for gateway to start...")
    time.sleep(20)
    
    host = os.environ["GATEWAY_HOST"] or "127.0.0.1"
    port = os.environ["GATEWAY_PORT"] or 4002
    print(f"Attempting to connect to gateway at {host}:{port}...")
    
    ib = IB()
    ib.connect(host=host, port=port, clientId=1)
    summary = ib.accountSummary()
    
    print(summary)
```
When I run the docker-compose, I get the following error: 
`bot-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 4004)`
This occurs after seeing the "Login has completed" message from ib-gateway.

Am I using the wrong IP/ports?  Additionally, is there an alternative to using the my hacky `time.sleep` work-around for making sure that the gateway is running?
