### ISSUE TITLE
using ib-gateway, live trade cannot login via IBC for 2FA input challenge code

### ISSUE THREAD

**Issue by xfocusinc** [gnzsnz/ib-gateway-docker#227]
## Describe the bug

In my `.env` file, I set `TRADING_MODE=live`, then run `docker-compose up`, basically hanging there, and client connection refused.

Meanwhile, if I just change the mode to be `paper` and switch to paper port 4002, login is success and client can list stocks successfully.

Maybe because paper trading does not have 2FA challenge code, but live trading does.

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/4782e96e-3010-430c-a6a3-02f5c88092d0" />

```
ib-gateway-1  | 2025-01-30 20:49:22:409 IBC: Setting Trading mode = live
ib-gateway-1  | 2025-01-30 20:49:22:492 IBC: Setting user name
ib-gateway-1  | 2025-01-30 20:49:22:493 IBC: Setting password
ib-gateway-1  | 2025-01-30 20:49:22:493 IBC: Login attempt: 1
ib-gateway-1  | 2025-01-30 20:49:22:507 IBC: Click button: Log In
ib-gateway-1  | 2025-01-30 20:49:23:471 IBC: detected frame entitled: IBKR Gateway; event=Lost focus
ib-gateway-1  | 2025-01-30 20:49:23:472 IBC: detected frame entitled: IBKR Gateway; event=Deactivated
ib-gateway-1  | 2025-01-30 20:49:23:472 IBC: detected frame entitled: Loading...; event=Activated
ib-gateway-1  | 2025-01-30 20:49:23:475 IBC: detected frame entitled: Loading...; event=Focused
ib-gateway-1  | 2025-01-30 20:49:23:475 IBC: detected frame entitled: Loading...; event=Opened
ib-gateway-1  | 2025-01-30 20:49:23:475 IBC: Found Gateway main window
ib-gateway-1  | 2025-01-30 20:49:23:475 IBC: Got main window from future
ib-gateway-1  | 2025-01-30 20:49:23:476 IBC: Invoking config dialog menu
ib-gateway-1  | 2025-01-30 20:49:24:065 IBC: detected frame entitled: Loading...; event=Lost focus
ib-gateway-1  | 2025-01-30 20:49:24:065 IBC: detected frame entitled: Loading...; event=Deactivated
ib-gateway-1  | 2025-01-30 20:49:24:065 IBC: detected frame entitled: Connecting to server...; event=Activated
ib-gateway-1  | 2025-01-30 20:49:24:065 IBC: detected frame entitled: Connecting to server...; event=Focused
ib-gateway-1  | 2025-01-30 20:49:24:065 IBC: detected frame entitled: Connecting to server...; event=Opened
ib-gateway-1  | 2025-01-30 20:49:24:789 IBC: detected dialog entitled: ** no title **; event=Opened
ib-gateway-1  | 2025-01-30 20:49:24:789 IBC: detected frame entitled: Authenticating...; event=Lost focus
ib-gateway-1  | 2025-01-30 20:49:24:789 IBC: detected frame entitled: Authenticating...; event=Deactivated
ib-gateway-1  | 2025-01-30 20:49:24:789 IBC: detected dialog entitled: ** no title **; event=Activated
ib-gateway-1  | 2025-01-30 20:49:24:790 IBC: detected dialog entitled: ** no title **; event=Focused



ib-gateway-1  | 2025/01/30 20:50:19 socat[151] E connect(5, AF=2 127.0.0.1:4001, 16): Connection refused
```

## To Reproduce

In my `.env` file, I set `TRADING_MODE=live`, then run `docker-compose up`, basically hanging there, and client connection refused.

```
name: algo-trader
services:
  ib-gateway:
    build:
      context: /Users/xx/workspace/investment/IbGateway/latest
      dockerfile: Dockerfile
      tags:
        - xx/ib-gateway:latest
      platforms:
        - linux/arm64
    environment:
      AUTO_LOGOFF_TIME: ""
      AUTO_RESTART_TIME: 11:59 PM
      BYPASS_WARNING: ""
      CUSTOM_CONFIG: "NO"
      JAVA_HEAP_SIZE: ""
      READ_ONLY_API: "no"
      RELOGIN_AFTER_TWOFA_TIMEOUT: "yes"
      SAVE_TWS_SETTINGS: ""
      SSH_ALIVE_COUNT: ""
      SSH_ALIVE_INTERVAL: ""
      SSH_OPTIONS: ""
      SSH_PASSPHRASE: ""
      SSH_REMOTE_PORT: ""
      SSH_RESTART: ""
      SSH_TUNNEL: ""
      SSH_USER_TUNNEL: ""
      SSH_VNC_PORT: ""
      TIME_ZONE: Europe/Zurich
      TRADING_MODE: live
      TWOFA_EXIT_INTERVAL: "60"
      TWOFA_TIMEOUT_ACTION: restart
      TWS_PASSWORD:
      TWS_PASSWORD_PAPER: ""
      TWS_SETTINGS_PATH: ""
      TWS_USERID:
      TWS_USERID_PAPER: ""
      TZ: Europe/Zurich
      VNC_SERVER_PASSWORD: myVncPassword
    image: xx/ib-gateway:latest
    networks:
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 4003
        published: "4001"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 4004
        published: "4002"
        protocol: tcp
      - mode: ingress
        target: 5900
        published: "5900"
        protocol: tcp
    restart: always
networks:
  default:
    name: algo-trader_default
```

## Expected

Should login successfully to ib-gateway live trading.
