### ISSUE TITLE
Read-only API not being set to `no`

### ISSUE THREAD

**Issue by gjtorikian** [gnzsnz/ib-gateway-docker#288]
## Describe the bug

Despite the fact that READ_ONLY_API is set to `no`, the gateway still sets the API to read-only.

## To Reproduce

1. Create a docker-compose.yml file similar to the example.
2. Run `docker-compose up`.
3. The logs state that the Read Only API is false:

    ```
    4|ib-gatew | ib-gateway_1  | 2025-06-30 10:22:21:107 IBC: Setting ReadOnlyApi
    4|ib-gatew | ib-gateway_1  | 2025-06-30 10:22:21:646 IBC: Read-Only API checkbox is now set to: false
    ```

4.  However, any trades attempted shows that the setting is not set:

    ```
    4|ib-gatew | ib-gateway_1  | 2025-06-30 10:24:56:442 IBC: detected dialog entitled: API client needs write access action confirmation; event=Activated
    ```

This happens with both `ib-gateway:latest` and `ib-gateway:stable`.

## Expected

API trades succeed.

## Container logs

See above showing the right setting being set.

## Versions

Please complete the following information:

- OS: `Ubuntu 22.04.4 LTS`
- Docker version:`Docker version 27.2.0, build 3ab4256`
- Image Tag (`docker image inspect ghcr.io/gnzsnz/ib-gateway:tag`): both `stable` and `latest`
- Image Digest (`docker images --digests`): for `stable`: `sha256:b8e3ce3043b7d7cd50f33d09f16720d2d05bdff341c2c90fcc599aaa9600a657`

## Additional context

docker-compose config:

```
name: ib-gateway-docker
services:
  ib-gateway:
    environment:
      ALLOW_BLIND_TRADING: "no"
      AUTO_LOGOFF_TIME: ""
      AUTO_RESTART_TIME: 06:00 AM
      BYPASS_WARNING: ""
      CUSTOM_CONFIG: "NO"
      EXISTING_SESSION_DETECTED_ACTION: primary
      JAVA_HEAP_SIZE: "6096"
      READ_ONLY_API: "no"
      RELOGIN_AFTER_TWOFA_TIMEOUT: "no"
      SAVE_TWS_SETTINGS: ""
      SSH_ALIVE_COUNT: ""
      SSH_ALIVE_INTERVAL: ""
      SSH_OPTIONS: ""
      SSH_PASSPHRASE: ""
      SSH_REMOTE_PORT: ""
      SSH_RESTART: ""
      SSH_TUNNEL: ""
      SSH_USER_TUNNEL: ""
      SSH_VNC_PORT: ""
      TIME_ZONE: America/New_York
      TRADING_MODE: live
      TWOFA_EXIT_INTERVAL: "60"
      TWOFA_TIMEOUT_ACTION: restart
      TWS_ACCEPT_INCOMING: manual
      TWS_COLD_RESTART: ""
      TWS_PASSWORD: florida1postman1
      TWS_SETTINGS_PATH: ""
      TWS_USERID: gjt321api
      TZ: America/New_York
      VNC_SERVER_PASSWORD: ""
    image: ghcr.io/gnzsnz/ib-gateway:stable
    networks:
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 4003
        published: "4001"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 4004
        published: "4002"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 5900
        published: "5900"
        protocol: tcp
    restart: always
networks:
  default:
    name: ib-gateway-docker_default
```
