### ISSUE TITLE
occasional interruption with java.lang.InteruptedException

### ISSUE THREAD

**Issue by josephchenhk** [gnzsnz/ib-gateway-docker#37]
**Describe the bug**

**To Reproduce**
follow all standard steps and run docker in Debian 7. Everthing works fine; but sometimes after a few hours, will disconnect and see the following error:

```
cta_strategy-ib-gateway-1  | 2023-11-02 08:28:35:471 IBC: detected dialog entitled: DU123456 Trader Workstation Configuration (Simulated Trading); event=Closed
cta_strategy-ib-gateway-1  | Forking :::4000 onto 0.0.0.0:4002
cta_strategy-ib-gateway-1  | remove Client 1
cta_strategy-ib-gateway-1  | remove Client 1
cta_strategy-ib-gateway-1  | 2023-11-02 12:32:03:935 IBC: detected frame entitled: Connecting to server...; event=Opened
cta_strategy-ib-gateway-1  | 2023-11-02 12:32:03:935 IBC: detected frame entitled: Connecting to server...; event=Activated
cta_strategy-ib-gateway-1  | 2023-11-02 12:32:03:936 IBC: detected frame entitled: Connecting to server...; event=Focused
cta_strategy-ib-gateway-1  | java.lang.InterruptedException
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
cta_strategy-ib-gateway-1  | 	at com.sun.javafx.application.PlatformImpl.waitForStart(PlatformImpl.java:256)
cta_strategy-ib-gateway-1  | 	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:277)
cta_strategy-ib-gateway-1  | 	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
cta_strategy-ib-gateway-1  | 	at com.sun.javafx.application.PlatformImpl.checkIdle(PlatformImpl.java:392)
cta_strategy-ib-gateway-1  | 	at com.sun.javafx.application.PlatformImpl.setImplicitExit(PlatformImpl.java:346)
cta_strategy-ib-gateway-1  | 	at javafx.application.Platform.setImplicitExit(Platform.java:138)
cta_strategy-ib-gateway-1  | 	at twslaunch.gstat.j.a(j.java:88)
cta_strategy-ib-gateway-1  | 	at twslaunch.gstat.a.d(a.java:215)
cta_strategy-ib-gateway-1  | 	at twslaunch.gstat.a.g(a.java:117)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cta_strategy-ib-gateway-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cta_strategy-ib-gateway-1  | 	at java.lang.Thread.run(Thread.java:748)
cta_strategy-ib-gateway-1  | 2023-11-02 12:32:37:902 IBC: detected frame entitled: Starting application...; event=Closed
```

**Expected behavior**
The connection should stay active; if it is interrupted, it should be able to resume automatically.

**Container logs**
If applicable, add the container logs `docker logs <CONTAINER>` or `docker-compose logs` to help explain your problem.

**Versions (please complete the following information):**
 - OS: [e.g. Windows]
 - Docker version: **Docker version 24.0.6**
 - Image Tag (`docker --version`): [e.g. latest]
 - Image Digest (`docker images --digests`): [e.g. sha256:60d9d54009b1b66908bbca1ebf5b8a03a39fe0cb35c2ab4023f6e41b55d17894] 

**Additional context**

Any ideas? Thanks.

**Comment by gnzsnz** [comment]
It could be related to the daily restart, please share the output of `docker compose config`. you will want to remove sensitive information like user and pass.

Personally I'm running a container with `AUTO_RESTART_TIME=08:59 AM` and it runs for a full week without any problem.

**Comment by josephchenhk** [comment]
Thanks very much for your reply.

My daily restart time is set to 06:05 AM, and it restarts as expected. So it might not be the issue. Anyway, here is my docker-compose.yml:

```
version: "3.4"

services:
  ib-gateway:
    image: ghcr.io/gnzsnz/ib-gateway:stable
    restart: always
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-live}
#      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      READ_ONLY_API: ${READ_ONLY_API:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
#    volumes:
#      - ${PWD}/jts.ini:/root/Jts/jts.ini
#      - ${PWD}/config.ini:/root/ibc/config.ini
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002"
#      - "127.0.0.1:5900:5900"
```

And here is my `.env` file (removed sensitive information):

```
TWS_USERID=XXX
TWS_PASSWORD=XXX
TRADING_MODE=paper
READ_ONLY_API=no
TWOFA_TIMEOUT_ACTION=restart
AUTO_RESTART_TIME=06:05 AM
RELOGIN_AFTER_2FA_TIMEOUT=yes
TIME_ZONE=Asia/Hong_Kong
CUSTOM_CONFIG=
```

Thanks.
